### ISSUE TITLE
ask about input dataset for knowing how to work it in libOpt

### ISSUE THREAD

**Issue by EhsnFrzdnia** [jppbsi/LibOPT-plus#1]
Hello
May I ask you how do I input a dataset with n variables as model file to this library for run in different kind of techniques?

Thank you

**Comment by jppbsi** [comment]
Hello,

Thanks for your interest. Do you wanna have "n" different for each problem? In this case, you must have a model file for each value o "n".

Best

**Comment by EhsnFrzdnia** [comment]
actually , I want to test my KDD99 dataset by LibOpt in MATLAB or CodeBlocks

**Comment by jppbsi** [comment]
Right, but what kind of optimization? Feature selection?

**Comment by EhsnFrzdnia** [comment]
these dataset have 41 feature (or variable) and a more than 4 million record of network traffics, actually , I want to decrease features by LibOpt

Thank you

**Comment by EhsnFrzdnia** [comment]
yes ,  Black Hole for example

**Comment by jppbsi** [comment]
Great, that's good. So, how many features do you have? I've worked with KDD99 in the past, but I don't remember, :o)

**Comment by gugarosa** [comment]
Ok, first of all, you need a metric to work with your dataset, correct? For instance, if you want to work with optimization and a dataset, there is the need to set a fitness function to evaluate your data.

Basically, we have divided our implementations in three main libraries: LibOPF (Pattern Recogniton), LibDEEP (Deep Learning) and LibOPT (Optimization). Therefore, we have a forth library that will integrate all these features, i.e., LibDEV (https://github.com/jppbsi/LibDEV).

If you check this file: https://github.com/jppbsi/LibDEV/blob/master/examples/FeatureSelection/FeatureSelectionOPF.c, it is already a ready-to-go implementation of Feature Selection, using the OPF classification as its fitness function (classification accuracy). You will only need to pass the depicted input parameters and change the optimization directive according to your needs, i.e., _BHA_.

I suggest that you also take a look at our wiki, in order to check what are our structures. Mainly, this one will allow you to understand the file format we use to our datasets: https://github.com/jppbsi/LibDEV/wiki/OPF-file-format-for-datasets

**Comment by jppbsi** [comment]
Thanks @gugarosa Now I see you have 41 features. Well, in this case, you must set the range of each variable in the model file, like that:

10 41 10 #\<n_particles\> \<dimension\> \<max_iterations\>
0 1 # lower and upper boundaries of feature 1 (this means 0 = feature will not be selected, and 1 = feature selected
0 1 # lower and upper boundaries of feature 2
.
.
.
0 1 # lower and upper boundaries of feature 41


But, as @gugarosa mentioned, you also need to define your fitness function. Have you tried OPF? Its a classifier that is totally integrated with LibOPT and it is quite easy to use.

**Comment by gugarosa** [comment]
Also, if you are having trouble to use your own data, we do have a ready-to-go NSL-KDD data, i.e., https://www.dropbox.com/s/mnog46xdqzy9zd0/nsl-kdd.tar.gz?dl=0

Its a shrinked version of KDD99, made by UNB (http://www.unb.ca/cic/research/datasets/nsl.html). If I'm not mistaken, it has 40 features with over 1 million records and it's already on the OPF file format.

**Comment by EhsnFrzdnia** [comment]
ok thank you .

**Comment by jppbsi** [comment]
Yep. Let us know.

**Comment by EhsnFrzdnia** [comment]
Sure

**Comment by EhsnFrzdnia** [comment]
hello again, how do I execute libOpt on Code:Blocks in Windows OS, and add it to Compiler ?  
when I run it , it prompts "No such file and directory" .

**Comment by gugarosa** [comment]
Do you have another OS to run? We had some issues while implementing for Windows, so we put it on a hold.

You could try to install MinGW for native gcc compiler on Windows, check if it's running from the command line and after try to build the library on CodeBlocks, but I'm not sure if it will work. As Windows have many issues regarding developing C libraries, we stopped working with it for now.

**Comment by EhsnFrzdnia** [comment]
Hello
I have a problem with LibOpt's Built in Code:Blocks.
I can not Build it , this error explain in that
"expected '}' not at end ... "
may you help me. 
may I send you screen shots of this problem in my desktop?

Thanks

**Comment by EhsnFrzdnia** [comment]
What is the Tensor ?

**Comment by EhsnFrzdnia** [comment]
ok, I successful to build and run it

**Comment by jppbsi** [comment]
Great you made it! With respect to Tensor, we've added a new type of search space, which is based on hypercomplex numbers. Recently, we proposed recently the Quaternion Harmony Search (http://rd.springer.com/chapter/10.1007/978-3-319-46182-3_11), where you can find helpful information about this tool. You can download the paper at the following link: https://www.researchgate.net/publication/305650202_On_the_Harmony_Search_Using_QuaternionsOn_the_Harmony_Search_Using_Quaternions

**Comment by EhsnFrzdnia** [comment]
Dear jppbsi,
I don't know how to use KDD99 Cup dataset instead of model file (BHA for e.g) for inputing  it.
please help in using it with BHA library.
Sincirely

**Comment by EhsnFrzdnia** [comment]
Do I convert KDD dataset to the model file format? 
How does The LibOpt work with KDD formats ?

**Comment by EhsnFrzdnia** [comment]
I tested The LibOpt in Code:Blocks with default BHA model file and changed its values over and over and differently , But I did not be able to test it with my kind KDD format when I want to input it to the LibOpt .

**Comment by EhsnFrzdnia** [comment]
I am appreciated you for taking your time to this position.

**Comment by jppbsi** [comment]
Hello,

Before trying to use BHA, I believe the best way would be to use one of the examples available at LibOPT/examples/FeatureSelection. Do you mind trying one of those first, please, and then we can work on the BHA.

Best,

**Comment by EhsnFrzdnia** [comment]
Hello
How do i can read a kdd cup file in csv format as matrix (41 Dimention)? what is its code in C ?
Thank you

**Comment by EhsnFrzdnia** [comment]
![try to load kdd cup as matrix to s](https://cloud.githubusercontent.com/assets/25326533/25457241/e4d2bbd4-2aea-11e7-81b8-6dab0c2a4266.jpg)

**Comment by EhsnFrzdnia** [comment]
I understood that must be changed this code to source code can be read from csv kdd cup .

**Comment by jppbsi** [comment]
You mean the highlighted code?

**Comment by EhsnFrzdnia** [comment]
yes

**Comment by EhsnFrzdnia** [comment]
it must be changed to code for reading  csv format kddcup99 reading , but what  ?

**Comment by EhsnFrzdnia** [comment]
my problem is reading from csv format kddcup 99 instead of generatenumbers from system , but i dont know how to do it ?

**Comment by jppbsi** [comment]
That code is just to initialize each decision variable within the predefined range. In order to do feature selection, you must have that. Actually, there is no need to change the source code of LibOPT. What you need to do is just to transform the .csv file into a .opf one. You can be in contact with another student of mine. His name is Clayton (claytontey@gmail.com). He can assist you in this task, since he has worked with kddcup and OPF before, ok?

**Comment by EhsnFrzdnia** [comment]
Thank You Professor .

**Comment by EhsnFrzdnia** [comment]
Hello
I have a question,
how do we set the LB and UB values for discrete feature ? for example if one of all features in data set can get only two acceptable value as this: 0 or 1, so, is it true that LB is '0' and UB also is '1, but actualy , this range is discrete not real. 
please lead me. 

Thank you.

**Comment by jppbsi** [comment]
Hello,

Please, take a look at the file LibDEV/examples/FeatureSelection/FeatureSelection.c. The loop in Lines 23-26 does that for you.

Best regards,

**Comment by EhsnFrzdnia** [comment]
Hello 

if a feature can accept only two values as 0 and 1, and be discrete,  could we consider LB and UB ranges as 0 and 1 by considering between these two LB and UB never be selected ?! 
my problem is that  i don't know if it is true to set this real valued rang (LB and UB) for a discrete valued feature or it is incorrect when i set LB and UB ranges for all real valued features in normalized kddcup data set at the same time?

is it correct to set LB and UB range values for a feature which is discrete and could only get two acceptable values as 0 or 1 , not between of them, not such as the other real valed featues?
if we set LB and UB for a feature is discrete, it will consider any values between of range LB and UB and it is not correct for in this case. in other word, we don't have to set LB and UB ranges for discrete features completely same as other real valued features in data set, have to? 

Thanks

**Comment by jppbsi** [comment]
Hello,

In the example I mentioned, we set the variables within the range [0,1]. You are right in wondering what is going on about that since we must use binary variables, i.e., {0,1}. However, the feature selection process uses a transfer function to map real-valued variables to binary ones. Therefore, you do not need to worry about that.

Best wishes,
